#!/usr/bin/env bash

echo DEBUG="$DEBUG"
echo POSTGRES_SCHEME="$POSTGRES_SCHEME"
echo POSTGRES_USER="$POSTGRES_USER"
echo POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
echo POSTGRES_HOST="$POSTGRES_HOST"
echo POSTGRES_PORT="$POSTGRES_PORT"
echo POSTGRES_PORT="POSTGRES_PORT"
echo POSTGRES_DB="$POSTGRES_DB"
echo POSTGRES_EXTERNAL_PORT="$POSTGRES_EXTERNAL_PORT"
echo ACCESS_TOKEN_EXPIRE_DAYS="$ACCESS_TOKEN_EXPIRE_DAYS"
echo SECRET_KEY="$SECRET_KEY"
echo ALGORITHM="$ALGORITHM"